JohnnyMorganz/luau-lsp

- .github/workflows/update-types-dump.yml
- CHANGELOG.md
- CMakeLists.txt
- README.md
- editors/code/src/extension.ts
- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
- src/AnalyzeCli.cpp
- src/LuauExt.cpp
- src/Workspace.cpp
- src/include/Analyze/AnalyzeCli.hpp
- src/include/LSP/LuauExt.hpp
- src/include/LSP/Workspace.hpp
- src/main.cpp
Merges https://github.com/JohnnyMorganz/luau-analyze-rojo into this project.
Main reason is to help simplify maintenance, as there is a lot of repeated code.
Entrypoint: `luau-lsp analyze`.
NOTE: This means the new entry point for the LSP is `luau-lsp lsp`
Not sure about naming, maybe we should rename the project to something which encompasses these tools together.
> Merge luau-analyze-rojo into project

- CHANGELOG.md
- CMakeLists.txt
- README.md
- editors/code/package.json
- src/LanguageServer.cpp
- src/LuauExt.cpp
- src/include/LSP/ClientConfiguration.hpp
- src/include/LSP/LanguageServer.hpp
- src/include/LSP/LuauExt.hpp
- src/include/LSP/Protocol.hpp
- src/include/LSP/Workspace.hpp
- src/operations/InlayHints.cpp
> Add support for inlay hints

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
> Retype functions

- .github/workflows/ci.yml
Ensure that globalTypes.d.lua is correct by running a smoketest on it
> Add types smoketest

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
> Correct WaitForChild type

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Replaces the definition of `function GetUserInfosByUserIdsAsync(self, userIds: { any }): { any }` with `	function GetUserInfosByUserIdsAsync(self, userIds: { number }): { { Id: number, Username: string, DisplayName: string } }`
> Correct type for `UserService:GetUserInfosByUserIdsAsync`

- CHANGELOG.md
- src/operations/InlayHints.cpp
> Hide inlay hint when variable = type name

- CHANGELOG.md
- src/AnalyzeCli.cpp
- src/LuauExt.cpp
- src/Workspace.cpp
- src/include/LSP/LuauExt.hpp
- src/include/LSP/Sourcemap.hpp
- src/include/LSP/Workspace.hpp
Attempted improvement for #112
> Improve instance type creation

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Improves diffs when adding corrections
> Sort class members in type definition generation script

- CHANGELOG.md
- CMakeLists.txt
- README.md
- src/LanguageServer.cpp
- src/include/LSP/LanguageServer.hpp
- src/include/LSP/Protocol.hpp
- src/include/LSP/SemanticTokens.hpp
- src/include/LSP/Workspace.hpp
- src/operations/SemanticTokens.cpp
- tests/Fixture.cpp
- tests/Fixture.h
- tests/SemanticTokens.test.cpp
> Implement Semantic Tokens

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Will add more corrections to this PR if I run into them
> Fix RunService:BindToRenderStep() type

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
> Add RBXScriptSignal:Once (again)

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Reverts JohnnyMorganz/luau-lsp#127
> Revert "Add RBXScriptSignal:Once (again)"

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Overridden members weren't listed in IGNORED_MEMBERS
> Fix duplicate methods for plugins

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
> Add `Enum:GetEnums()`

- scripts/globalTypes.d.lua
Reverts JohnnyMorganz/luau-lsp#181
> Revert "Update to latest types dump"

- CHANGELOG.md
- CMakeLists.txt
- src/LuauExt.cpp
- src/operations/Completion.cpp
- tests/Diagnostics.test.cpp
- tests/Fixture.cpp
- tests/Fixture.h
> Provide autocomplete/diagnostics on classnames to `Instance:IsA()`

- CHANGELOG.md
- src/LuauExt.cpp
- src/operations/Completion.cpp
- tests/Diagnostics.test.cpp
> Provide autocomplete/diagnostics for GetPropertyChangedSignal

- CHANGELOG.md
- CMakeLists.txt
- src/DocumentationParser.cpp
- src/include/LSP/DocumentationParser.hpp
- src/include/LSP/Workspace.hpp
- src/operations/Completion.cpp
- src/operations/Hover.cpp
- src/operations/SignatureHelp.cpp
- tests/Documentation.test.cpp
- tests/Fixture.cpp
- tests/Fixture.h
Closes #5 
Currently only supports comments attached directly to functions
> Support documentation comments

- CHANGELOG.md
- src/LuauExt.cpp
- src/operations/Completion.cpp
- tests/Diagnostics.test.cpp
- tests/Fixture.cpp
> Provide autocomplete/diagnostics for EnumItem:IsA("Enum")

- CHANGELOG.md
- CMakeLists.txt
- src/LanguageServer.cpp
- src/include/LSP/LanguageServer.hpp
- src/include/LSP/Workspace.hpp
- src/include/Protocol/LanguageFeatures.hpp
- src/include/Protocol/ServerCapabilities.hpp
- src/operations/ColorProvider.cpp
Closes #217 
Haven't done brick colors for now
Gated behind `luau-lsp.types.roblox`
> Add color provider support to Color3

- CHANGELOG.md
- editors/code/syntaxes/lua.tmLanguage.json
- src/operations/SemanticTokens.cpp
Fixes #237 
Its probably worth recreating the syntaxes file from scratch
> Syntax highlighting improvements

- CHANGELOG.md
- src/LanguageServer.cpp
- src/Workspace.cpp
- src/operations/Completion.cpp
Closes #202 
https://user-images.githubusercontent.com/19635171/211879448-24363e34-136c-4cb0-a902-0fa909b953ce.mp4
> Autocomplete require-by-string

- CHANGELOG.md
- editors/code/package.json
- editors/code/src/extension.ts
- src/DocumentationParser.cpp
- src/LanguageServer.cpp
- src/include/LSP/Client.hpp
- src/include/LSP/DocumentationParser.hpp
- src/include/LSP/LanguageServer.hpp
- src/main.cpp
An alternative solution for #271
> Support user-defined documentation files

- CHANGELOG.md
- src/LuauExt.cpp
- src/operations/Completion.cpp
> Prioritise autocompletion of common services and instance properties

- CHANGELOG.md
- CMakeLists.txt
- README.md
- src/LanguageServer.cpp
- src/LuauExt.cpp
- src/include/LSP/LanguageServer.hpp
- src/include/LSP/LuauExt.hpp
- src/include/LSP/Utils.hpp
- src/include/LSP/Workspace.hpp
- src/include/Protocol/ClientCapabilities.hpp
- src/include/Protocol/CodeAction.hpp
- src/include/Protocol/ServerCapabilities.hpp
- src/operations/CodeAction.cpp
- src/operations/Completion.cpp
https://user-images.githubusercontent.com/19635171/218266886-d4ca83ba-a163-47f5-8f34-6d25bf07b97d.mp4
Can also be run automatically on save by configuring
```json
"editor.codeActionsOnSave": {
"source.organizeImports": true
}
```
https://user-images.githubusercontent.com/19635171/218268532-b967a0d8-0192-4a50-912f-cbd5b3a99944.mp4
> Implement sort requires and services code actions

- CHANGELOG.md
- src/operations/ColorProvider.cpp
> Add color picker changing support

- CHANGELOG.md
- src/operations/FoldingRange.cpp
> Add folding range for function definitions

- CHANGELOG.md
- src/operations/Completion.cpp
> Force relative imports when in model project

- CHANGELOG.md
- src/include/LSP/Workspace.hpp
- src/operations/Completion.cpp
> Support auto-requiring modules in types

- CHANGELOG.md
- editors/code/package.json
- src/Utils.cpp
- src/WorkspaceFileResolver.cpp
- src/include/LSP/ClientConfiguration.hpp
- src/include/LSP/Utils.hpp
- src/include/LSP/WorkspaceFileResolver.hpp
- src/operations/Completion.cpp
- tests/Utils.test.cpp
- tests/WorkspaceFileResolver.test.cpp
> Support require directory aliases and tilde expansion

- CHANGELOG.md
- editors/code/package.json
- src/TextDocument.cpp
- src/include/LSP/ClientConfiguration.hpp
- src/operations/Completion.cpp
> Autocomplete end in function calls

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Closes #376 
TODO: we need to define an indexer on SharedTable
> Add SharedTable definition

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
> Let Value be nillable in ObjectValue

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Incorrectly typed as `function SendMessage(self, topic: string, message: any): nil` (message should be ...any)
> Fix Actor:SendMessage

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.lua
Fixes `OpenCloudModel` not being defined
> Manual type dump generation

- CHANGELOG.md
- src/LuauExt.cpp
- tests/Rename.test.cpp
> Rename local should also rename imported types

- scripts/dumpRobloxTypes.py
Adds floor division type to Vector3
> Add Vector3 floor division type

- scripts/dumpRobloxTypes.py
Roblox's Luau implementation supports this.
> Support floor division in Vector2 & Vector3

- CHANGELOG.md
- src/Uri.cpp
- tests/Uri.test.cpp
> Fix unicode handling in Uris

- .github/workflows/ci.yml
- scripts/dumpRobloxTypes.py
Fix Raycast definition, and make sure we always test the python script in CI
> Fix types dump

- scripts/dumpRobloxTypes.py
This PR reverts changes made in #558 and #560
> Revert RaycastResult changes

- scripts/DataTypes.json
made this which should fix #581
> made Vector2int16.new params optional

- src/platform/roblox/RobloxCompletion.cpp
> Fix autocomplete importing . as service or not importing service

- scripts/DataTypes.json
This adds Path2DControlPoint with its constructor and type definition.
> Fully Add Path2DControlPoint

- scripts/dumpRobloxTypes.py
- scripts/globalTypes.d.luau
`TeleportService:TeleportToPlaceInstance` `player` argument being optional is unchanged and correct.
> Fix `teleportData` types

- src/Workspace.cpp
Introduced in https://github.com/JohnnyMorganz/luau-lsp/commit/e8b31d3d8b8b06d3a25891acaa722ed55c883f10
> Fix platform being initialized twice

- scripts/dumpRobloxTypes.py
> Fix outdated github username in dumpRobloxTypes

- CHANGELOG.md
> Sync to upstream Luau 0.650

- CHANGELOG.md
- tests/main.cpp
> Sync to upstream Luau 0.652

- CHANGELOG.md
- editors/code/package.json
- src/AnalyzeCli.cpp
- src/WorkspaceFileResolver.cpp
- src/include/LSP/ClientConfiguration.hpp
- src/include/LSP/WorkspaceFileResolver.hpp
- src/include/Platform/LSPPlatform.hpp
- src/main.cpp
- src/platform/LSPPlatform.cpp
- tests/Autocomplete.test.cpp
- tests/Fixture.cpp
- tests/Fixture.h
- tests/WorkspaceFileResolver.test.cpp
> Support `.luaurc` aliases

- CMakeLists.txt
- src/WorkspaceFileResolver.cpp
- tests/Workspace.test.cpp
Fixes #802 
Fixes #583 
Supersedes #805
> Handle URI-based module names in managed files lookup

- scripts/DataTypes.json
Closes #911 
This PR fixes the types of Faces and Axes datatypes.
> Fix Types for Faces and Axes datatypes

- scripts/DataTypes.json
> Fix Vector2:Angle return type

- CHANGELOG.md
- CMakeLists.txt
- editors/code/package.json
- editors/code/src/extension.ts
- src/Client.cpp
- src/JsonRpc.cpp
- src/include/LSP/Client.hpp
- src/include/LSP/JsonRpc.hpp
- src/include/LSP/Transport/PipeTransport.hpp
- src/include/LSP/Transport/StdioTransport.hpp
- src/include/LSP/Transport/Transport.hpp
- src/main.cpp
- src/transport/PipeTransport.cpp
- src/transport/StdioTransport.cpp
- tests/TestClient.cpp
- tests/TestClient.h
> Support pipe communication

- CHANGELOG.md
- src/Client.cpp
- src/LanguageServer.cpp
- src/Uri.cpp
- src/Utils.cpp
- src/Workspace.cpp
- src/WorkspaceFileResolver.cpp
- src/include/LSP/Client.hpp
- src/include/LSP/Uri.hpp
- src/include/LSP/Utils.hpp
- src/include/LSP/Workspace.hpp
- src/include/LSP/WorkspaceFileResolver.hpp
- src/include/Protocol/Diagnostics.hpp
- src/include/Protocol/Structures.hpp
- src/operations/CodeAction.cpp
- src/operations/Completion.cpp
- src/operations/Diagnostics.cpp
- src/operations/Rename.cpp
- src/operations/WorkspaceSymbol.cpp
- src/platform/roblox/RobloxCodeAction.cpp
- src/platform/roblox/RobloxCompletion.cpp
- tests/Autocomplete.test.cpp
- tests/Rename.test.cpp
- tests/Sourcemap.test.cpp
- tests/Uri.test.cpp
- tests/Workspace.test.cpp
> Make Uri hashable and use it as a key, remove lowercase normalisation

- CHANGELOG.md
- src/LanguageServer.cpp
- src/Workspace.cpp
- src/WorkspaceFileResolver.cpp
- src/include/LSP/LanguageServer.hpp
- src/include/LSP/Workspace.hpp
- src/include/Protocol/Lifecycle.hpp
- src/operations/Diagnostics.cpp
- src/platform/LSPPlatform.cpp
- src/platform/roblox/RobloxFileResolver.cpp
- tests/AutoImports.test.cpp
- tests/Definitions.test.cpp
- tests/Fixture.cpp
- tests/LanguageServer.test.cpp
> Lazily initialize workspaces

- scripts/dumpRobloxTypes.py
This PR changes the return type of methods on enums from any to actual enum
> Improve Enum Type Returns

- scripts/DataTypes.json
Additional constructor I missed in SecurityCapabilities.
> Add SecurityCapabilities.fromCurrent

- CHANGELOG.md
- CMakeLists.txt
- editors/README.md
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/extension.ts
- editors/code/src/requireGraph.ts
- src/LanguageServer.cpp
- src/include/LSP/Workspace.hpp
- src/include/Protocol/Extensions.hpp
- src/operations/RequireGraph.cpp
- tests/RequireGraph.test.cpp
> Add require graph support
