JohnnyMorganz/luau-lsp

.github/workflows/release.yml, editors/code/package.json
- Use zip for binaries
- Skip packaging extensions, instead publish directly
- Copy LICENSE into extension
- Remove need to build macos binary twice, now only built once with 2 targets specified
=> Update release workflow

CHANGELOG.md, README.md, editors/code/package-lock.json, editors/code/package.json, editors/code/src/extension.ts, src/Workspace.cpp, src/include/LSP/Client.hpp, src/include/LSP/LanguageServer.hpp, src/main.cpp
Paths to definition files can be added in `luau-lsp.types.definitionFiles`
Roblox types can be disabled using `luau-lsp.types.roblox`
Part of #29 
Also related to #40
=> Add support for registering definition files

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Apply a toposort when writing out the data types, so that we don't resolve to `any`
Fixes #111 
Blocked on https://github.com/Roblox/luau/issues/652 as this change will produce false positives
=> Toposort data types in definitions file

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
These used `Instance` rather than `Player`, and in `TeleportInitFailed`, used `Instance` instead of `TeleportOptions`
=> Correct types for `TeleportService` events

CHANGELOG.md, CMakeLists.txt, aftman.toml, editors/code/package-lock.json, editors/code/package.json, editors/code/src/extension.ts, editors/code/src/test/suite/index.ts, editors/code/tsconfig.json, foreman.toml, plugin/.gitignore, plugin/README.md, plugin/default.project.json, plugin/selene.toml, plugin/src/init.lua, plugin/src/init.server.lua, plugin/test.project.json, src/LanguageServer.cpp, src/StudioPlugin.cpp, src/WorkspaceFileResolver.cpp, src/include/LSP/LanguageServer.hpp, src/include/LSP/PluginDataModel.hpp, src/include/LSP/Sourcemap.hpp, src/include/LSP/WorkspaceFileResolver.hpp
This PR creates a Studio plugin which provides Instance information directly from Studio to the Language Server.
This is useful for partially managed projects.
When a connection is initialised, we listen for changes to the DataModel in Studio. These are then sent to the LanguageServer. The DM info provided is then merged with the existing sourcemap to provide more instance info.
Todo:
Future work:
- Handle script contents so you can require code that is only present in Studio
- Delta changes rather than full-sync each change
Closes #81
=> Add Studio Plugin support

.github/workflows/nightly.yml
Handles #51 
We create a workflow which will build the server and extension every day at midnight UTC. It will be available to download from the action artifacts for users who want to use/test latest main
=> Create nightly workflow

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Many methods used `Instance` rather than `BasePart`
`GetNetworkOwner` may be nil
=> BasePart type improvements

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Fixes types:
`Camera.CameraSubject` could possibly be `nil`. It's valid types are `BasePart` and `Humanoid`
`Team:GetPlayers()` return a list of `Player`s
`Teams:GetTeams` return a list of `Team`s
`AncestryChanged`'s second signal argument may be nil if the ancestor's parent became `nil`.
`FindFirstChild...` and `FindFirstAncestor...` methods didn't return `Instance?`
`WorldRoot:GetPart...` returns an array of `{ BasePart }`
and some more
`GetPartsObscuringTarget` does in fact take a list of `Instance`s, not `BasePart`s
`Teams:GetTeams()` causes the type definition file to fail to load due to complexity, so the tests will probably fail. I can split it off from this PR.
=> More type improvements

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
This will probably fail because it causes too much complexity in the type definitions file
=> Correct return type for Teams:GetTeams()

CHANGELOG.md, src/operations/Completion.cpp
This PR improves the ordering of autocomplete items by utilising sort text.
We provide items in the following order:
1) variables which match the correct type
2) functions which return the correct type
3) catch-all local and global variables
4) (Index/Calls only) property with incorrect index (i.e. suggest `foo.prop` for `foo:`, or `foo:call` on `foo.`)
5) Automatic Imports
6) General Lua keywords (and/or/then etc.)
Closes #156
=> Improve Completion Ordering

CHANGELOG.md, src/LanguageServer.cpp, src/LuauExt.cpp, src/TextDocument.cpp, src/Workspace.cpp, src/WorkspaceFileResolver.cpp, src/include/LSP/LanguageServer.hpp, src/include/LSP/LuauExt.hpp, src/include/LSP/TextDocument.hpp, src/include/LSP/WorkspaceFileResolver.hpp, src/operations/Completion.cpp, src/operations/Diagnostics.cpp, src/operations/DocumentSymbol.cpp, src/operations/GotoDefinition.cpp, src/operations/Hover.cpp, src/operations/InlayHints.cpp, src/operations/References.cpp, src/operations/Rename.cpp, src/operations/SemanticTokens.cpp, src/operations/SignatureHelp.cpp, tests/TextDocument.test.cpp
Fixes #42 
We now correctly handle UTF-16 encoded Positions sent by the client.
Our internal representation of the text document is now correct, and does not lead to malformed issues.
We also properly convert from and to UTF-16 positions before processing the code / sending it back to the client.
`lsp::Position` is now treated as a UTF-16 encoded position, whilst `Luau::Position` is UTF-8
=> Improve handling of UTF-16 encoded Positions

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
The "parameters" to signals created by `GetInstanceAddedSignal` and `GetInstanceRemovedSignal` were typed as `...any`, instead of `Instance`
This also marks `GetAttributeChangedSignal` and `GetPropertyChangedSignal` as returning signals that don't pass anything
Refines `Humanoid.SeatPart` to be `Seat | VehicleSeat | nil`, rather than `BasePart?`
=> Type improvements

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Only allow valid identifiers as properties (previously we "escaped" them, but they were incorrect and provide no benefit)
=> Update to latest types dump + only valid identifiers

CHANGELOG.md, src/operations/InlayHints.cpp
=> Fix inlay hints not showing when `hover.strictDatamodelTypes` is disabled

CHANGELOG.md, src/operations/Diagnostics.cpp
We accidently were creating diagnostics before applying the check to see if the error applies to the current text document. This meant we were using the current text document to create type errors that weren't part of this document, causing string errors due to UTF-8/16 conversions.
=> Fix workspace diagnostics type errors creation

CHANGELOG.md, src/AnalyzeCli.cpp, src/main.cpp
Adds support for ignoring errors from certain files using the glob pattern. The option is prefixed with; `--ignoreGlobs=`, adding multiple options with the same prefix should also work. 
This MR addresses [#176 ](https://github.com/JohnnyMorganz/luau-lsp/issues/176)
Note: I'm fairly "new" to C++ had some university experience with it, but I'm certainly not a pro. With that in mind, please criticize anything that I could fix/improve!
=> Add ignore glob support for analyze

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
`GetPlayerByUserId` and `GetPlayerFromCharacter` may return `nil` if player wasn't found
the second Player parameter in chatted events will be nil if the chat wasn't a whisper.
`GuiService.SelectedObject` may be nil if nothing is selected
Removed type correction for `Player:GetPlayers()` as it's no longer needed
=> Type corrections for Players, Player, and GuiService

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Fixed none of the functions types returning the second `DataStoreKeyInfo` type.
Made `OrderedDataStore` only be able to use numbers as the value, since passing any other type to the function will error with `103: string is not allowed in data stores.`
`SetAsync` returns a `string` that stores the version's id
Fixed the `transformFunction`'s type in `UpdateAsync`
=> Fix types for datastores

.gitattributes, scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Luau doesn't like it when `Highlight.Adornee` is nil even though this is valid through the Roblox properties window.
`scripts/globalTypes.d.lua` has also been enforced to use LF line endings.
=> Override Highlight.Adornee property

CHANGELOG.md, src/LuauExt.cpp, src/include/LSP/Sourcemap.hpp
Fixes #254 
The problem was that `getSourcemapType` returns a cached type if it already exists, but the cached type was created for `frontend.typeChecker`, not `frontend.typeCheckerForAutocomplete`. The `Instance` global ty is different for the two type checkers.
This meant that DM types in autocomplete mode were subtypes of the base type checker global Instance ty, not the autocomplete version, so unification would fail.
To fix this, we create a different ty for general use and autocomplete mode
=> Fix incorrect Instance ty ptr causing failed unification and `never` types

CHANGELOG.md, src/DocumentationParser.cpp, src/operations/Hover.cpp, tests/Documentation.test.cpp
This PR adds in support for documentation comments attached to local variables, functions defined through `local var = function()` syntax, and table properties:
```lua
--- documentation comment
local x = "string"
--- another doc comment
local y = function()
end
local tbl = {
--- This is some special information
data = "hello",
--- This is a doc comment
values = function()
end,
}
local x = tbl.values -- Should give "This is a doc comment"
local y = tbl.data -- Should give "This is some special information"
```
Closes #247 
Also support a variable number of `=` signs used to denote a multiline documentation comment (Closes #236)
```lua
--[[
Adds 5 to the input number
@param x number -- The number to add 5 to
@return number -- Returns `x` with 5 added to it
]]
function add5(x: number)
return …
```
=> Support more documentation comments

CHANGELOG.md, editors/code/package.json, src/WorkspaceFileResolver.cpp, src/include/LSP/ClientConfiguration.hpp, src/include/LSP/Workspace.hpp, src/include/LSP/WorkspaceFileResolver.hpp, src/operations/Completion.cpp
Adds a new config option `luau-lsp.require.mode`:
- `relativeToWorkspaceRoot` (default)
- `relativeToFile`
Closes #272
=> Support relative-to-file string requires

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Adds the missing Vector3:Angle function to the type definitions.
=> Add Vector3:Angle to type def

CHANGELOG.md, src/DocumentationParser.cpp, src/LanguageServer.cpp, src/Workspace.cpp, src/WorkspaceFileResolver.cpp, src/include/LSP/WorkspaceFileResolver.hpp, src/operations/ColorProvider.cpp, src/operations/Completion.cpp, src/operations/Diagnostics.cpp, src/operations/DocumentSymbol.cpp, src/operations/GotoDefinition.cpp, src/operations/Hover.cpp, src/operations/InlayHints.cpp, src/operations/References.cpp, src/operations/Rename.cpp, src/operations/SemanticTokens.cpp, src/operations/SignatureHelp.cpp, tests/Fixture.cpp
We also have to normalise document URI to lowercase on windows/mac to deal with case insensitive file systems
We leave "getTextDocumentFromModuleName" for simplicity
Hopefully fixes #267
=> Switch to using document URI to store managed files

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
Fix the `Handles.Adornee` & `ArcHandles.Adornee` property type (the property can be nil).
Additionally, fix the `Highlight.Adornee` property from a previous change I made. The Adornee property should probably only stick to BaseParts per the Roblox docs.
=> Fix Handles/ArcHandles.Adornee type

scripts/dumpRobloxTypes.py, scripts/globalTypes.d.lua
`Highlight.Adornee` was actually supposed to remain as an `Instance?`, my bad. I forgot that Highlights supported models.
It also looks like Roblox pushed a `SharedTableRegistry` service that uses a `SharedTable` type that wasn't defined in the globalTypes dump, causing analysis to error for the CLI. How do you typically handle this?
=> Revert Highlight.Adornee property type + add SharedTable definition

CHANGELOG.md, CMakeLists.txt, editors/code/package.json, src/LanguageServer.cpp, src/LuauExt.cpp, src/Workspace.cpp, src/include/LSP/ClientConfiguration.hpp, src/include/LSP/LuauExt.hpp, src/include/LSP/Workspace.hpp, src/operations/References.cpp, src/operations/Rename.cpp, tests/Fixture.cpp, tests/References.test.cpp
Adds support for proper cross-module find all references.
Also adds support for finding references of types (both local and exported, cross-module)
This also adds in a workspace indexing system, which will be useful for #124 as well
These improvements are also extended to rename support
Closes #117
TODO:
- Find all references of a require? We only do table properties right now
=> Improved Find All References and Rename

CHANGELOG.md, src/LanguageServer.cpp, src/Workspace.cpp, src/include/LSP/Workspace.hpp, src/operations/CallHierarchy.cpp, src/operations/CodeAction.cpp, src/operations/ColorProvider.cpp, src/operations/Completion.cpp, src/operations/Diagnostics.cpp, src/operations/DocumentLink.cpp, src/operations/DocumentSymbol.cpp, src/operations/FoldingRange.cpp, src/operations/GotoDefinition.cpp, src/operations/Hover.cpp, src/operations/InlayHints.cpp, src/operations/References.cpp, src/operations/Rename.cpp, src/operations/SemanticTokens.cpp, src/operations/SignatureHelp.cpp, src/operations/WorkspaceSymbol.cpp
Right now we retain all type graphs all the time, for both diagnostics and autocomplete typecheckers.
This causes *a lot* of types to be stored. For a standard sample workspace, I hit over 2GB of memory used. For a more complex workspace, this can increase several times further.
We update this by being more clever about retaining type graphs. We only retain type graphs if we later require the type information to power a Language Server feature. For example, when we indexed the whole workspace, we don't actually care about the types, but just about the require graph. In this case, we discard the type graph, and lazily compute the retain type graph in the actual Find All References operation. Similarly, workspace diagnostics does not require the type graph at all.
This leads to a …
=> Be more clever about retaining type graphs

src/DocumentationParser.cpp, tests/Documentation.test.cpp
Some Markdown parsers require an explicit paragraph break between a list block and the previous block. Sublime's LSP appears to be one of them.
No explicit break:
```markdown
**Parameters**
- `foo`  Description of foo.
- `bar`  Description of bar.
```
Explicit break:
```markdown
**Parameters**
- `foo`  Description of foo.
- `bar`  Description of bar.
```
This change adds a single newline after each section header to create the paragraph break necessary for list blocks to be interpreted correctly. Markdown parsers that do not require this paragraph break should continue parse normally.
=> Add paragraph break in generated documentation to ensure correct parsing

CHANGELOG.md, CMakeLists.txt, src/include/Protocol/Structures.hpp, src/operations/Rename.cpp, tests/Fixture.cpp, tests/Fixture.h, tests/Rename.test.cpp
Fixes #488 and some other test cases
A generic type parameter can be defined in three locations:
- A type alias definition `type Foo<S> = ...`
- A type function `<T>(T) -> T`
- A function expression `function foo<T>(x: T)`
We handle renaming type parameters in these cases.
To do so, we check to see whether the provided position is within one of the relevant spots, and if so, use a visitor to find all usages of the type parameter.
A type parameter can also be shadowed in one way in particular: a type function embedded inside of a type alias definition / function expression. We handle this case as well.
There is a special case when the node found to be renamed is a `AstTypeReference` - in this case, we compute the Ast ancestry to find the top level where the generic type was defined.
=> Handle renaming generic type parameters

scripts/dumpRobloxTypes.py
Normally `RaycastResult.Instance` should be `BasePart`, but sometimes its `Attachment | Constraint` (which is why Roblox defines it as Instance).
Using generics to handle this case switch would make the typechecking less annoying.
=> Redefine RaycastResult with generics.

scripts/dumpRobloxTypes.py
Small oversight that might’ve broken the latest update. Apologies for missing this!
=> Fix function definition error with GizmoRaycast.

.gitignore, CHANGELOG.md, extern/doctest/doctest.h, src/Utils.cpp, src/WorkspaceFileResolver.cpp, src/include/LSP/Utils.hpp, tests/Utils.test.cpp, tests/WorkspaceFileResolver.test.cpp
This PR fixes behaviour of `FindFirstAncestor` when trying to `require` one of the children of root instance of non-DataModel project.
```json
{
"name": "Root",
"tree": {
"$path": "src"
}
}
```
=> Fix `FindFirstAncestor` in non-DataModel projects

scripts/Corrections.json, scripts/DataTypes.json, scripts/dumpRobloxTypes.py
This PR fixes missing/wrong datatype types
Changes:
```
- CFrame  
- CFrame.LookAlong(at: Vector3,direction: Vector3,up: Vector3) 
- CFrame.fromEulerAngles(rx: number,ry: number,rz: number,order: Enum.RotationOrder) 
- CFrame.new():ToEulerAngles(order: Enum.RotationOrder):number,number,number 
- PathWayPoint 
- PathWayPoint.new().Label (and 3rd arg of new was missing)
- PhysicalProperties 
-  new(density: number,friction: number,elasticity: number) is missing 
- Rect 
-  Rect.new() (params are not required) 
- Secret 
-  Secret is not in the list at all
-  HttpService:GetSecret():AddPrefix 
- HttpService:GetSecret():AddSuffix 
- Vector2 
- Vector2.max 
- Vector2.min 
- Vector2.new():Abs 
- Vector2.new():Ceil 
- Vector2.new():Floor 
- Vector2.new():Sign 
- Vector2.new():Angle 
- Vector3 
- …
```
=> Datatype type fixes

scripts/dumpRobloxTypes.py
this PR adds debug.getmemorycategory() to type definitions
=> Add getmemorycategory to type definitions

src/platform/roblox/RobloxFileResolver.cpp
This quick fix solves this problem with the JSON and TOML files:
> Only click-to-follow feature works but the actual completion does not. Additionally, it throws TypeError: Unknown require error.
as discussed in #553.
=> Fix requiring `JSON` and `TOML` modules

scripts/DataTypes.json
`BundleType` isn't actually a valid member of a `CatalogSearchParams`.
=> fix "BundleType"

plugin/src/init.server.lua
I think it was mentioned like a week ago that plugin connection feedback would probably be added eventually, so I propose a quick fix here.
Only changes made are the added message, and passing the isSilent parameter to use it as a condition for the message.
Keep in mind I haven't actually tested this, I just read the plugin code and coded the message where I think is most appropriate, since setting up the plugin testing environment is took much of a headache for me, since I've never done it.
At the very least if my implementation sucks, this is a reminder that this 'feature' should be simple to implement, and to put it in the to-do list.
=> Add plugin feedback for plugin-server connection

CHANGELOG.md, CMakeLists.txt, src/LanguageServer.cpp, src/Workspace.cpp, src/include/LSP/Workspace.hpp, tests/Definitions.test.cpp, tests/Fixture.cpp, tests/Fixture.h, tests/testdata/extra_definitions_relying_on_mutations.d.luau
Fixes #658 
Changes:
- Previously, the workspace-global definitions file metadata (`definitionsMetadata`) was set to the metadata of the last definitions file that contained metadata. Now, it is set to the first one. I think this makes sense as it prevents the platform metadata from getting overridden.
- Since the language server does not do anything useful before the platform is available, `WorkspaceFolder::initialize` (which only performed type registration) was moved to `setupWithConfiguration` and renamed to `registerTypes`.
- The platform mutation function is now run after every definition file is registered. The platform can disambiguate which definitions file is which by checking what types are available (how it was done before) or with the metadata provided in the file.
This …
=> Fix loading type definitions that rely on mutation

CHANGELOG.md
This PR syncs the upstream Luau version to 0.645. I confirmed locally that everything builds without issue, so no additional changes needed beyond upgrading the Luau commit.
=> Sync to upstream Luau 0.645

scripts/DataTypes.json
Closes #800 and #768
this PR adds `fromRotationBetweenVectors` and `FuzzyEq` to CFrame datatype
=> Add CFrame.fromRotationBetweenVectors

scripts/DataTypes.json
this PR adds types for Content Datatype
=> Add Content Datatype types

scripts/DataTypes.json
Expands on #817 - `Content.none` is part of the constructor table for this DataType (and not of the type itself)
Example:
```luau
-- valid
imageLabel.ImageContent = Content.none
-- "none is not a valid member of Content"
local c = Content.fromUri("")
print(c.none == Content.none)
```
=> Move Content.none to the constructor table

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/upload-companion-plugin.yml, .gitignore, .stylua.toml, aftman.toml, plugin/cloud/execute_task.luau, plugin/cloud/publishing_task.luau, plugin/selene.toml
Right now, the Studio companion plugin must still be manually published to Roblox after updates.
With the introduction of the new AssetService creation APIs (https://devforum.roblox.com/t/beta-lua-asset-creation-for-creator-tooling-with-createassetasync/3294134/18), alongside the OpenCloud APIs to execute Luau in the engine (https://devforum.roblox.com/t/beta-open-cloud-engine-api-for-executing-luau/3172185), we can now automate this flow!
We develop a Lune script to support executing arbitrary cloud tasks in the engine. `test.project.json` builds a barebones place file with the plugin built at `game.ReplicatedStorage.Plugin`.
After building the place file with Rojo, the execute task script will upload it to Roblox, then execute the provided cloud task file.
We also add in a cloud task …
=> Create workflows to publish Companion plugin

scripts/dumpRobloxTypes.py, scripts/globalTypes.LocalUserSecurity.d.luau, scripts/globalTypes.None.d.luau, scripts/globalTypes.PluginSecurity.d.luau, scripts/globalTypes.RobloxScriptSecurity.d.luau, scripts/globalTypes.d.lua, scripts/globalTypes.d.luau
Not all sounds have a SoundGroup associated with them. I found out this flaw in one of my scripts I ported to Rojo and analysed in strict mode
=> Make `Sound.SoundGroup` optional

src/LanguageServer.cpp, src/platform/roblox/RobloxStudioPlugin.cpp
https://github.com/JohnnyMorganz/luau-lsp/blob/a82ebc1823fa74fa358c8401ff2c7adcf0ea7aa7/src/LanguageServer.cpp#L342-L348
We don't return `true` so we still hit "unknown notification method" even if handled
=> fix: return value in Roblox platform notification handler

CHANGELOG.md, editors/code/package.json, editors/code/src/extension.ts
This PR adds a configuration value (`luau-lsp.serverPath`) to the VSCode extension that lets you change the path of the Luau LSP server binary. This is useful for platforms like NixOS, where the included binary doesn't work by default. This hasn't been tested yet.
=> Add server path configuration option to the VSCode extension

CHANGELOG.md, editors/code/package.json, editors/code/src/extension.ts, src/include/LSP/ClientConfiguration.hpp, src/include/LSP/Workspace.hpp, src/operations/Completion.cpp, tests/Autocomplete.test.cpp
Fragment based autocomplete is an optimisation to the autocomplete system that reuses previous typechecking data for a module and applies patches on top based on the code changes. This allows Luau to update the type representation of a module without having to recheck the whole module from scratch, leading to a performance improvement for autocompletion.
This PR enables fragment autocompletion for luau-lsp. This is currently gated behind the `luau-lsp.completion.enableFragmentAutocomplete` setting.
Closes #825
=> Introduce support for Luau's fragment-based autocomplete

CHANGELOG.md, src/AnalyzeCli.cpp, src/include/Analyze/AnalyzeCli.hpp, tests/AnalyzeCli.test.cpp
Closes #892.
Note: I have near to no C++ experience so my solution may not be optimal. However, it does work.
=> Load ignore globs and definition files from settings file

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, CHANGELOG.md
The latest release (1.39.1) caused an unintended bump in the minimum supported macOS version.
Let's make it explicit that we support macOS 10.15 onwards. 10.15 is the minimum version that supports the necessary APIs in use
=> Set minimum macOS version to 10.15

plugin/src/init.server.lua
made both PluginToolbarButton ClickableWhenViewportHidden = true
Currently when I'm editing Plugin Settings and want to reconnect I'd have to exit out of the Script which is annoying if I want to try re-connecting
I don't see a reason why ClickableWhenViewportHidden should be kept as false
=> Set PluginToolbarButton ClickableWhenViewportHidden to true

scripts/dumpRobloxTypes.py
`ContentId` is the new name for what was previously the `Content` type, before the actual Content type was introduced.
I can't auto-complete string methods on ContentId properties at the moment because of the `any` type. It should be `string`.
=> Re-alias ContentId as string, remove Content alias.

CHANGELOG.md, editors/code/src/extension.ts, src/DocumentationParser.cpp
This PR enables HTML support by adding `supportHtml: true` to the language client options and removing the `convertHtmlToMarkdown` function, which previously just removed the HTML tags from documentation.
I assume other language clients also support HTML (perhaps with a similar option that just needs to be toggled on?).
=> Enable HTML rendering in language client options

CHANGELOG.md, src/include/LSP/Uri.hpp, tests/Rename.test.cpp
It turns out that if a key is not `std::string`, or not implicitly convertible to a string, then nlohmann will serialize the final `unordered_map` as an array of pairs: https://github.com/nlohmann/json/issues/2132
This caused the result of Rename and other workspace edits to be malformed when sent to VSCode, causing those commands to fail
=> Fix JSON serialization of unordered map keyed by Uri

CHANGELOG.md, src/Uri.cpp, src/include/LSP/Uri.hpp, src/platform/StringRequireAutoImporter.cpp, tests/AutoImports.test.cpp
The code that checks whether the full file path starts with the aliased value is incorrect on windows:
- `uri.path` contains a leading `/` (`/c:/Users/Development/...`)
- the drive letter can be of different case (`c:/` vs `C:/`)
We fix this by using Uris directly: we introduce a new `Uri::isAncestorOf(other)` method, and use `Uri::lexicallyRelative` for resolving the remainder path to add to the alias.
Fixes #1025
=> Fix aliases not used for string require auto-imports on Windows

scripts/dumpRobloxTypes.py
This PR adds FromValue and FromName Methods to Enum.
Return type is `any` since we can't return the actual enum (`Enum.AssetType:FromValue()` returns `Enum.Assettype?` in studio)
=> Add FromValue and FromName Methods to Enum

CHANGELOG.md, CMakeLists.txt, scripts/release.py, src/LanguageServer.cpp, src/main.cpp
Adds information about LSP to the initialization result, so it can be used by lsp integrations (e.g. JB IDE plugin)
=> feat: add server info to lsp initialize results

scripts/DataTypes.json
This pull request adds Roblox's `SecurityCapabilities` datatype to luau-lsp.
Tested in a local branch, resulting type definition file works as intended 🎉
=> Add SecurityCapabilities DataType

scripts/dumpRobloxTypes.py
Recently I have been working with `TextChatService` and observed that its children instances are not detected by the LSP.
The [`TextChatService` documentation](https://create.roblox.com/docs/reference/engine/classes/TextChatService) says,
> For further customization, TextChatService has the following singleton children:
> 
>     [ChatWindowConfiguration](https://create.roblox.com/docs/reference/engine/classes/ChatWindowConfiguration)
>     [ChatInputBarConfiguration](https://create.roblox.com/docs/reference/engine/classes/ChatInputBarConfiguration)
>     [BubbleChatConfiguration](https://create.roblox.com/docs/reference/engine/classes/BubbleChatConfiguration)
>     [ChannelTabsConfiguration](https://create.roblox.com/docs/reference/engine/classes/ChannelTabsConfiguration)
Each instance is …
=> Add TextChatService children configurations
